# fly.toml app configuration file generated for bus-fares on 2025-07-29T21:37:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bus-fares'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
